# Generated by Django 5.0.7 on 2024-07-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
